language: java
sudo: required

#before_install:
#  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

install: true
script:
  - mvn install

services:
  - docker

after_success:
  - sh .travis/deploy_dockerhub.sh
#  - test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY