language: java
install: true
script:
  - mvn install

services:
  - docker

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh

#deploy:
#  provider: heroku
#  api_key:
#    secure: 479872e2-377c-4623-946d-674237cbde2b