version: '3'
services:
  postgres:
    image: postgres
    container_name: db
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'test'
      PGDATA: /var/lib/postgresql/data/pgdata

  timetracker:
    container_name: test_app
    build: .
    ports:
    - 4001:8080